/**
 * Comprehensive fallback demo dataset for BazaarMind.
 * Ensures the prototype functions gracefully even when offline or during deployment transitions.
 * All data here is clearly marked as DEMO.
 */

export const DEFAULT_MARKETS = [
  {
    id: "demo-ina",
    name: "INA MARKET — BAZAARMIND DEMO",
    area: "South Delhi, Delhi NCR",
    community: "Green Meadows RWA (demo community)",
    lat: 28.5687,
    lng: 77.2094,
    synthetic: true,
    distanceKm: 0.0,
    intelligenceAvailable: true,
  },
  {
    id: "demo-sarojini",
    name: "Sarojini Nagar Market",
    area: "South West Delhi, Delhi NCR",
    community: "Sarojini RWA (demo)",
    lat: 28.5775,
    lng: 77.1969,
    synthetic: true,
    distanceKm: 1.56,
    intelligenceAvailable: false,
    discoveryOnly: true,
  },
  {
    id: "demo-ghazipur",
    name: "Ghazipur Mandi",
    area: "East Delhi, Delhi NCR",
    community: "Kondli RWA (demo)",
    lat: 28.6255,
    lng: 77.3255,
    synthetic: true,
    distanceKm: 12.98,
    intelligenceAvailable: false,
    discoveryOnly: true,
  },
];

export const DEFAULT_DEMO_PULSE = {
  marketId: "demo-ina",
  products: [
    {
      product: "Tomatoes",
      availability: "Tight",
      availabilityCode: "LOW",
      demand: "Elevated",
      demandCode: "HIGH",
      reportedPriceSignal: "₹65–₹72/kg",
      priceLow: 65,
      priceHigh: 72,
      priceUnit: "kg",
      vendorObservations: 5,
      independentVendors: 4,
      independentStallsCount: 4,
      shopperSignals: 8,
      signalCount: 13,
      confidence: "High",
      conflicting: false,
      lastUpdatedMinutes: 12,
      lastUpdated: "12m ago",
      evidence: [
        {
          id: "ev-t1",
          source: "VENDOR",
          sourceLabel: "Vendor observation",
          observedValue: "₹70/kg · Availability: Tight",
          reportedPrice: 70,
          priceUnit: "kg",
          availability: "LOW",
          rawText: "Aaj tamatar thoda kam aaya hai aur rate 70 rupaye hai.",
          confidence: "HIGH",
          timeAgo: "15m ago",
          vendorName: "Ramesh Sabzi Wala",
          dataSource: "DEMO",
        },
        {
          id: "ev-t2",
          source: "VENDOR",
          sourceLabel: "Vendor observation",
          observedValue: "₹68/kg · Availability: Tight",
          reportedPrice: 68,
          priceUnit: "kg",
          availability: "LOW",
          rawText: "Tomato stock tight today across local stalls.",
          confidence: "HIGH",
          timeAgo: "45m ago",
          vendorName: "Green Basket",
          dataSource: "DEMO",
        },
        {
          id: "ev-t3",
          source: "SHOPPER",
          sourceLabel: "Shopper demand",
          observedValue: "2 kg requested",
          rawText: "Mujhe 2 kilo tamatar chahiye",
          confidence: "MEDIUM",
          timeAgo: "22m ago",
          dataSource: "DEMO",
        },
      ],
      evidenceSignals: [
        {
          id: "ev-t1",
          source: "VENDOR",
          sourceLabel: "Vendor observation",
          observedValue: "₹70/kg · Availability: Tight",
          reportedPrice: 70,
          priceUnit: "kg",
          availability: "LOW",
          rawText: "Aaj tamatar thoda kam aaya hai aur rate 70 rupaye hai.",
          confidence: "HIGH",
          timeAgo: "15m ago",
          vendorName: "Ramesh Sabzi Wala",
          dataSource: "DEMO",
        },
        {
          id: "ev-t2",
          source: "VENDOR",
          sourceLabel: "Vendor observation",
          observedValue: "₹68/kg · Availability: Tight",
          reportedPrice: 68,
          priceUnit: "kg",
          availability: "LOW",
          rawText: "Tomato stock tight today across local stalls.",
          confidence: "HIGH",
          timeAgo: "45m ago",
          vendorName: "Green Basket",
          dataSource: "DEMO",
        },
      ],
    },
    {
      product: "Potatoes",
      availability: "Good",
      availabilityCode: "HIGH",
      demand: "Normal",
      demandCode: "NORMAL",
      reportedPriceSignal: "₹24–₹28/kg",
      priceLow: 24,
      priceHigh: 28,
      priceUnit: "kg",
      vendorObservations: 4,
      independentVendors: 4,
      independentStallsCount: 4,
      shopperSignals: 5,
      signalCount: 9,
      confidence: "High",
      conflicting: false,
      lastUpdatedMinutes: 18,
      lastUpdated: "18m ago",
      evidence: [
        {
          id: "ev-p1",
          source: "VENDOR",
          sourceLabel: "Vendor observation",
          observedValue: "₹25/kg · Availability: Good",
          reportedPrice: 25,
          priceUnit: "kg",
          availability: "HIGH",
          rawText: "Aloo ka stock pura hai, 25 rupaye rate.",
          confidence: "HIGH",
          timeAgo: "18m ago",
          vendorName: "Fresh Corner",
          dataSource: "DEMO",
        },
      ],
      evidenceSignals: [
        {
          id: "ev-p1",
          source: "VENDOR",
          sourceLabel: "Vendor observation",
          observedValue: "₹25/kg · Availability: Good",
          reportedPrice: 25,
          priceUnit: "kg",
          availability: "HIGH",
          rawText: "Aloo ka stock pura hai, 25 rupaye rate.",
          confidence: "HIGH",
          timeAgo: "18m ago",
          vendorName: "Fresh Corner",
          dataSource: "DEMO",
        },
      ],
    },
    {
      product: "Onions",
      availability: "Good",
      availabilityCode: "HIGH",
      demand: "Normal",
      demandCode: "NORMAL",
      reportedPriceSignal: "₹30–₹35/kg",
      priceLow: 30,
      priceHigh: 35,
      priceUnit: "kg",
      vendorObservations: 4,
      independentVendors: 4,
      independentStallsCount: 4,
      shopperSignals: 6,
      signalCount: 10,
      confidence: "High",
      conflicting: false,
      lastUpdatedMinutes: 25,
      lastUpdated: "25m ago",
      evidence: [
        {
          id: "ev-o1",
          source: "VENDOR",
          sourceLabel: "Vendor observation",
          observedValue: "₹32/kg · Availability: Good",
          reportedPrice: 32,
          priceUnit: "kg",
          availability: "HIGH",
          rawText: "Pyaz achha aaya hai aaj, 32 rupaye kilo.",
          confidence: "HIGH",
          timeAgo: "25m ago",
          vendorName: "Sharma Fruits",
          dataSource: "DEMO",
        },
      ],
      evidenceSignals: [
        {
          id: "ev-o1",
          source: "VENDOR",
          sourceLabel: "Vendor observation",
          observedValue: "₹32/kg · Availability: Good",
          reportedPrice: 32,
          priceUnit: "kg",
          availability: "HIGH",
          rawText: "Pyaz achha aaya hai aaj, 32 rupaye kilo.",
          confidence: "HIGH",
          timeAgo: "25m ago",
          vendorName: "Sharma Fruits",
          dataSource: "DEMO",
        },
      ],
    },
    {
      product: "Coriander",
      availability: "Tight",
      availabilityCode: "LOW",
      demand: "Elevated",
      demandCode: "HIGH",
      reportedPriceSignal: "₹25–₹30/bunch",
      priceLow: 25,
      priceHigh: 30,
      priceUnit: "bunch",
      vendorObservations: 4,
      independentVendors: 3,
      independentStallsCount: 3,
      shopperSignals: 7,
      signalCount: 11,
      confidence: "High",
      conflicting: false,
      lastUpdatedMinutes: 30,
      lastUpdated: "30m ago",
      evidence: [],
      evidenceSignals: [],
    },
    {
      product: "Lemon",
      availability: "Normal",
      availabilityCode: "NORMAL",
      demand: "Normal",
      demandCode: "NORMAL",
      reportedPriceSignal: "₹8–₹10/piece",
      priceLow: 8,
      priceHigh: 10,
      priceUnit: "piece",
      vendorObservations: 3,
      independentVendors: 3,
      independentStallsCount: 3,
      shopperSignals: 4,
      signalCount: 7,
      confidence: "Medium",
      conflicting: false,
      lastUpdatedMinutes: 40,
      lastUpdated: "40m ago",
      evidence: [],
      evidenceSignals: [],
    },
    {
      product: "Banana",
      availability: "Normal",
      availabilityCode: "NORMAL",
      demand: "Normal",
      demandCode: "NORMAL",
      reportedPriceSignal: "₹55–₹60/dozen",
      priceLow: 55,
      priceHigh: 60,
      priceUnit: "dozen",
      vendorObservations: 3,
      independentVendors: 3,
      independentStallsCount: 3,
      shopperSignals: 5,
      signalCount: 8,
      confidence: "Medium",
      conflicting: false,
      lastUpdatedMinutes: 35,
      lastUpdated: "35m ago",
      evidence: [],
      evidenceSignals: [],
    },
    {
      product: "Chilli",
      availability: "Tight",
      availabilityCode: "LOW",
      demand: "Elevated",
      demandCode: "HIGH",
      reportedPriceSignal: "₹80–₹95/kg",
      priceLow: 80,
      priceHigh: 95,
      priceUnit: "kg",
      vendorObservations: 3,
      independentVendors: 3,
      independentStallsCount: 3,
      shopperSignals: 6,
      signalCount: 9,
      confidence: "Medium",
      conflicting: false,
      lastUpdatedMinutes: 45,
      lastUpdated: "45m ago",
      evidence: [],
      evidenceSignals: [],
    },
  ],
  overallConfidence: "High",
  totalSignals: 94,
  lastUpdated: "12m ago",
  synthetic: true,
  dataSource: "DEMO",
  market: {
    id: "demo-ina",
    name: "INA MARKET — BAZAARMIND DEMO",
    area: "South Delhi, Delhi NCR",
    community: "Green Meadows RWA (demo community)",
    lat: 28.5687,
    lng: 77.2094,
    synthetic: true,
  },
};

export const DEFAULT_NETWORK = {
  marketId: "demo-ina",
  shopperSignals: 59,
  supplySignals: 38,
  vendors: [
    { id: "v1", name: "Ramesh Sabzi Wala", stall: "Stall 3 · INA Mandi", supplySignals: 12 },
    { id: "v2", name: "Sharma Fruits", stall: "Stall 7 · Fruit Row", supplySignals: 9 },
    { id: "v3", name: "Green Basket", stall: "Stall 11 · Center Lane", supplySignals: 10 },
    { id: "v4", name: "Fresh Corner", stall: "Stall 14 · Main Gate", supplySignals: 7 },
  ],
};

export const DEFAULT_VENDORS = [
  {
    vendorId: "v1",
    vendorName: "Ramesh Sabzi Wala",
    stallName: "Stall 3 · Fresh Greens",
    distanceKm: 0.12,
    lat: 28.56885,
    lng: 77.20925,
    googleMapsUrl: "https://www.google.com/maps/dir/?api=1&destination=28.56885,77.20925",
    offers: [
      { product: "Tomatoes", reportedPrice: 70, priceUnit: "kg" },
      { product: "Potatoes", reportedPrice: 25, priceUnit: "kg" },
      { product: "Coriander", reportedPrice: 25, priceUnit: "bunch" },
    ],
  },
  {
    vendorId: "v2",
    vendorName: "Sharma Fruits",
    stallName: "Stall 7 · Fruit Row",
    distanceKm: 0.24,
    lat: 28.56895,
    lng: 77.20950,
    googleMapsUrl: "https://www.google.com/maps/dir/?api=1&destination=28.56895,77.20950",
    offers: [
      { product: "Banana", reportedPrice: 58, priceUnit: "dozen" },
      { product: "Apple", reportedPrice: 150, priceUnit: "kg" },
    ],
  },
  {
    vendorId: "v3",
    vendorName: "Green Basket",
    stallName: "Stall 11 · Center Lane",
    distanceKm: 0.35,
    lat: 28.56860,
    lng: 77.20960,
    googleMapsUrl: "https://www.google.com/maps/dir/?api=1&destination=28.56860,77.20960",
    offers: [
      { product: "Onions", reportedPrice: 32, priceUnit: "kg" },
      { product: "Chilli", reportedPrice: 90, priceUnit: "kg" },
    ],
  },
  {
    vendorId: "v4",
    vendorName: "Fresh Corner",
    stallName: "Stall 14 · Main Gate",
    distanceKm: 0.18,
    lat: 28.56850,
    lng: 77.20915,
    googleMapsUrl: "https://www.google.com/maps/dir/?api=1&destination=28.56850,77.20915",
    offers: [
      { product: "Spinach", reportedPrice: 28, priceUnit: "bunch" },
      { product: "Ginger", reportedPrice: 130, priceUnit: "kg" },
      { product: "Carrots", reportedPrice: 38, priceUnit: "kg" },
      { product: "Lemon", reportedPrice: 9, priceUnit: "piece" },
    ],
  },
];

export const DEFAULT_SNAPSHOTS = [
  {
    id: "snap-1",
    label: "Yesterday (Morning)",
    changes: [
      { product: "Tomatoes", field: "Availability", from: "Normal", to: "Tight" },
      { product: "Onions", field: "Reported Price", from: "₹28/kg", to: "₹32/kg" },
    ],
  },
  {
    id: "snap-2",
    label: "2 Days Ago",
    changes: [
      { product: "Potatoes", field: "Reported Price", from: "₹22/kg", to: "₹25/kg" },
      { product: "Spinach", field: "Availability", from: "Good", to: "Tight" },
    ],
  },
];

export const DEFAULT_TRENDS = {
  products: [
    {
      product: "Tomatoes",
      points: [
        { date: "2026-09-20", priceMid: 62, availability: "Normal" },
        { date: "2026-09-21", priceMid: 65, availability: "Normal" },
        { date: "2026-09-22", priceMid: 68, availability: "Tight" },
        { date: "2026-09-23", priceMid: 70, availability: "Tight" },
        { date: "2026-09-24", priceMid: 72, availability: "Tight" },
      ],
    },
    {
      product: "Potatoes",
      points: [
        { date: "2026-09-20", priceMid: 24, availability: "Good" },
        { date: "2026-09-21", priceMid: 25, availability: "Good" },
        { date: "2026-09-22", priceMid: 25, availability: "Good" },
        { date: "2026-09-23", priceMid: 26, availability: "Good" },
        { date: "2026-09-24", priceMid: 26, availability: "Good" },
      ],
    },
    {
      product: "Onions",
      points: [
        { date: "2026-09-20", priceMid: 30, availability: "Good" },
        { date: "2026-09-21", priceMid: 32, availability: "Good" },
        { date: "2026-09-22", priceMid: 32, availability: "Good" },
        { date: "2026-09-23", priceMid: 34, availability: "Good" },
        { date: "2026-09-24", priceMid: 33, availability: "Good" },
      ],
    },
  ],
};

export const DEFAULT_DEMAND = {
  totalRequests: 42,
  products: [
    { product: "Tomatoes", level: "High demand · 18 shopper requests" },
    { product: "Onions", level: "Elevated demand · 12 shopper requests" },
    { product: "Coriander", level: "Elevated demand · 8 shopper requests" },
    { product: "Spinach", level: "Moderate demand · 6 shopper requests" },
  ],
};

export const DEFAULT_PILOT_METRICS = {
  setup: {
    community: "Green Meadows RWA",
    market: "INA MARKET — BAZAARMIND DEMO",
    vendors: "10–15 stalls",
    households: "20–50 homes",
    durationDays: 14,
  },
  metrics: [
    { name: "Daily Active Signals", target: "50+ signals / day", status: "Active" },
    { name: "Vendor Stall Check-ins", target: "8+ stalls / day", status: "Active" },
    { name: "Shopper Accuracy Rating", target: "> 85% helpfulness", status: "Target" },
    { name: "WhatsApp Retention", target: "> 60% week-2 return", status: "Pilot" },
  ],
};

export const DEFAULT_PILOT_STATUS = {
  environment: "DEMO",
  hasPilotData: true,
  metrics: [
    { name: "Registered Markets", display: "3 markets (Delhi NCR)" },
    { name: "Demonstration Pulse", display: "7 active product signals" },
    { name: "Gemini Model", display: "gemini-3.5-flash-lite (Live)" },
    { name: "Location Provider", display: "Google Places + GPS" },
    { name: "Corroboration Confidence", display: "High (Synthetic baseline)" },
  ],
};

export const DEFAULT_HISTORY = {
  history: [
    { capturedAt: "2026-09-24T02:00:00Z", totalSignals: 24 },
    { capturedAt: "2026-09-23T02:00:00Z", totalSignals: 20 },
  ],
  comparison: {
    available: true,
    changes: [
      { product: "Tomatoes", field: "Reported Price", from: "₹60–₹65/kg", to: "₹65–₹72/kg" },
      { product: "Coriander", field: "Availability", from: "Good", to: "Tight" },
    ],
  },
};
